Huvikool/Models/Space.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huvikool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Space
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Space()
        {
            this.Activities = new HashSet<Activity>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Ruumi nimi")]
        public string Name { get; set; }
        [Display(Name = "Ruumi nr")]
        public string Placement { get; set; }
        [Display(Name = "Kirjeldus")]
        public string Description { get; set; }
        [Display(Name = "Mahutavus")]
        public Nullable<int> Limit { get; set; }
        [Display(Name = "Foto")]
        public Nullable<int> PictureId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual DataFile DataFile { get; set; }
    }
}

Huvikool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Huvikool.Models;
using System.IO;

namespace Huvikool.Controllers
{

    public class MyController : Controller
    {
        protected TagaridaEntities5 db = new TagaridaEntities5();
        [OutputCache(Duration = 3600, VaryByParam = "id", Location = System.Web.UI.OutputCacheLocation.Any)]
        public ActionResult Content(int? id)
        {
            DataFile df = db.DataFiles.Find(id);
            if (df == null) return HttpNotFound();
            return File(df.Content, df.ContentType);
        }

        public Person CurrentPerson = null; // siis on hea kohe see PersonObject omale taskusse panna
        public void CheckPerson()
        {
            if (Request.IsAuthenticated)        // kontrollida vaja vaid siis
                if ((CurrentPerson?.Email ?? "") != User.Identity.Name)    // kui juba ei ole meeles või on vale
                    using (TagaridaEntities5 db = new TagaridaEntities5())
                    {
                        CurrentPerson = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                        if (CurrentPerson == null)
                        {
                            using (ApplicationDbContext dba = new ApplicationDbContext())
                            {
                                ApplicationUser u = dba.Users.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                                db.People.Add(CurrentPerson = new Person
                                {
                                    Email = User.Identity.Name,
                                    FirstName = u.FirstName,
                                    LastName = u.LastName,
                                    BirthDate = u.BirthDate,

                                });
                                db.SaveChanges();
                            }
                        }
                    }
                else CurrentPerson = null;
        }
        protected void ChangeDataFile(HttpPostedFileBase file, Action<int> change, int? oldId)
        {
            if (file != null && file.ContentLength > 0)
                using (BinaryReader br = new BinaryReader(file.InputStream))
                {
                    DataFile df = new DataFile
                    {
                        Content = br.ReadBytes(file.ContentLength),
                        FileName = file.FileName.Split('\\').Last().Split('/').Last(),
                        ContentType = file.ContentType,
                        Created = DateTime.Now
                    };
                    db.DataFiles.Add(df);
                    db.SaveChanges();
                    change(df.Id);
                    if (oldId.HasValue)
                    {
                        db.DataFiles.Remove(db.DataFiles.Find(oldId.Value));
                        db.SaveChanges();
                    }

                }
        }

    }




    public class HomeController : MyController
    {
        public ActionResult Index()
        {
            CheckPerson();
            if (Request.IsAuthenticated)
            {
                TagaridaEntities5 db = new TagaridaEntities5();
                //ViewBag.Kasutaja = User.Identity.Name;
                //Person p = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                //if (p == null)
                //    return RedirectToAction("Create", "People", new { email = User.Identity.Name });
                //    //ViewBag.Person = "Meile tundmatu";
                //else
                //    ViewBag.Person = p.FirstName;


            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Huvikool on loodud aastal 2017.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Võta meiega ühendust või astu läbi!";

            return View();
        }
    }
}

Huvikool/Controllers/SpacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Huvikool.Models;

namespace Huvikool.Controllers
{
    public class SpacesController : MyController
    {
        private TagaridaEntities5 db = new TagaridaEntities5();

        // GET: Spaces
        public ActionResult Index()
        {
            var spaces = db.Spaces;//.Include(s => s.DataFile);
            return View(spaces.ToList());
        }

        // GET: Spaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Space space = db.Spaces.Find(id);
            if (space == null)
            {
                return HttpNotFound();
            }
            return View(space);
        }

        // GET: Spaces/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Spaces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Placement,Description,Limit,PictureId")] Space space, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Spaces.Add(space);
                db.SaveChanges();
                ChangeDataFile(
                    file,
                    x => { space.PictureId = x; db.SaveChanges(); },
                    space.PictureId);

                return RedirectToAction("Index");
            }

            
            return View(space);
        }

        // GET: Spaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Space space = db.Spaces.Find(id);
            if (space == null)
            {
                return HttpNotFound();
            }
            
            return View(space);
        }

        // POST: Spaces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Placement,Description,Limit,PictureId")] Space space, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(space).State = EntityState.Modified;
                db.SaveChanges();
                ChangeDataFile(
                    file,
                    x => { space.PictureId = x; db.SaveChanges(); },
                    space.PictureId);

                return RedirectToAction("Index");
            }
            
            return View(space);
        }

        // GET: Spaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Space space = db.Spaces.Find(id);
            if (space == null)
            {
                return HttpNotFound();
            }
            return View(space);
        }

        // POST: Spaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Space space = db.Spaces.Find(id);
            db.Spaces.Remove(space);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Huvikool/Views/Spaces/Create.cshtml
@model Huvikool.Models.Space

@{
    ViewBag.Title = "Create";
}

<h2>Lisa uus ruum</h2>


@using (Html.BeginForm("Create", "Spaces", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.PictureId)
        @*<h4>Space</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Placement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Placement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Limit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Limit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Limit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Lisa pilt</p>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
                @*<img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
                @Html.HiddenFor(x => x.PictureId)*@
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi ruumide nimekirja", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#datafile').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
    });</script>

Huvikool/Views/Spaces/Delete.cshtml
@model Huvikool.Models.Space

@{
    ViewBag.Title = "Delete";
}

<h2>Kustuta</h2>

<h3>Kas sa oled kindel, et soovid ruumi kustutada?</h3>
<div>
    @*<h4>Space</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Limit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Limit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFile.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFile.ContentType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Kustuta" class="btn btn-default" /> |
            @Html.ActionLink("Tagasi ruumide nimekirja", "Index")
        </div>
    }
</div>

Huvikool/Views/Spaces/Details.cshtml
@model Huvikool.Models.Space

@{
    ViewBag.Title = "Details";
}

<h2>Detailid</h2>

<div>
    @*<h4>Space</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Limit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Limit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFile.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFile.ContentType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Muuda", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Tagasi ruumide nimekirja", "Index")
</p>

Huvikool/Views/Spaces/Edit.cshtml
@model Huvikool.Models.Space

@{
    ViewBag.Title = "Edit";
}

<h2>Muuda ruumi</h2>


@using (Html.BeginForm("Edit", "Spaces", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Space</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.PictureId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Placement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Placement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Limit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Limit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Limit, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <p class="control-label col-md-2">Change picture</p>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
                <img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
                @Html.HiddenFor(x => x.PictureId)
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvesta" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi ruumide nimekirja", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#datafile').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
    });</script>

Huvikool/Views/Spaces/Index.cshtml
@model IEnumerable<Huvikool.Models.Space>

@{
    ViewBag.Title = "Index";
}

<h2>Meie ruumid</h2>

<p>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Lisa uus", "Create")
    }
    </p>
<p>
    Praegusel hetkel on meil kasutuses 5 erinevat ruumi, mida on võimalik ka rentida majavälisteks üritusteks
    ja kursusteks.
<p><a href="~/Home/Contact" class="btn btn-primary btn-sm">Võta meiega ühendust&raquo;</a></p>
</p>
<div class="row">
    @foreach (var item in Model)
    {
    <div class="col-md-4">


        <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
        <p>@Html.DisplayFor(modelItem => item.Description)</p>
        <img src="@Url.Action("Content", "My", new {id = item.PictureId})" height="200" />
        <p>Mahutavus: @Html.DisplayFor(model => item.Limit) inimest </p>
        <p>Ruumi number: @Html.DisplayFor(model => item.Placement)</p>
        @if (User.IsInRole("Admin"))
        {<ul>

            <li>
                @Html.ActionLink("Muuda", "Edit", new { id = item.Id })
            </li>

            <li>
                @Html.ActionLink("Detailid", "Details", new { id = item.Id })
            </li>
            <li>
                @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
            </li>
        </ul>
        }

        @*@Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
        @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })*@
    </div>

    }
</div>
@*</div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Limit)
            </th>
            <th>
                Foto
                @Html.DisplayNameFor(model => model.DataFile.ContentType)
            </th>
            <th></th>
        </tr>*@

@*@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Limit)
         <div class="row">
        @foreach (var item in Model)
        {
        <div class="col-md-4">


            <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
            <p>@Html.DisplayFor(modelItem => item.Description)</p>
            <img src="@Url.Action("Content", "My", new {id = item.PictureId})" height="200" />

            @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
            @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
        </div>

          }
    </div>
    }

    </table>*@