Huvikool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Huvikool.Models;
using System.IO;

namespace Huvikool.Controllers
{

    public class MyController : Controller
    {
        protected TagaridaEntities5 db = new TagaridaEntities5();
        [OutputCache(Duration = 3600, VaryByParam = "id", Location = System.Web.UI.OutputCacheLocation.Any)]
        public ActionResult Content(int? id)
        {
            DataFile df = db.DataFiles.Find(id);
            if (df == null) return HttpNotFound();
            return File(df.Content, df.ContentType);
        }

        public Person CurrentPerson = null; // siis on hea kohe see PersonObject omale taskusse panna
        public void CheckPerson()
        {
            if (Request.IsAuthenticated)        // kontrollida vaja vaid siis
                if ((CurrentPerson?.Email ?? "") != User.Identity.Name)    // kui juba ei ole meeles või on vale
                    using (TagaridaEntities5 db = new TagaridaEntities5())
                    {
                        CurrentPerson = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                        if (CurrentPerson == null)
                        {
                            using (ApplicationDbContext dba = new ApplicationDbContext())
                            {
                                ApplicationUser u = dba.Users.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                                db.People.Add(CurrentPerson = new Person
                                {
                                    Email = User.Identity.Name,
                                    FirstName = u.FirstName,
                                    LastName = u.LastName,
                                    BirthDate = u.BirthDate,

                                });
                                db.SaveChanges();
                            }
                        }
                    }
                else CurrentPerson = null;
        }
        protected void ChangeDataFile(HttpPostedFileBase file, Action<int> change, int? oldId)
        {
            if (file != null && file.ContentLength > 0)
                using (BinaryReader br = new BinaryReader(file.InputStream))
                {
                    DataFile df = new DataFile
                    {
                        Content = br.ReadBytes(file.ContentLength),
                        FileName = file.FileName.Split('\\').Last().Split('/').Last(),
                        ContentType = file.ContentType,
                        Created = DateTime.Now
                    };
                    db.DataFiles.Add(df);
                    db.SaveChanges();
                    change(df.Id);
                    if (oldId.HasValue)
                    {
                        db.DataFiles.Remove(db.DataFiles.Find(oldId.Value));
                        db.SaveChanges();
                    }

                }
        }

    }




    public class HomeController : MyController
    {
        public ActionResult Index()
        {
            CheckPerson();
            if (Request.IsAuthenticated)
            {
                TagaridaEntities5 db = new TagaridaEntities5();
                //ViewBag.Kasutaja = User.Identity.Name;
                //Person p = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                //if (p == null)
                //    return RedirectToAction("Create", "People", new { email = User.Identity.Name });
                //    //ViewBag.Person = "Meile tundmatu";
                //else
                //    ViewBag.Person = p.FirstName;


            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Huvikool on loodud aastal 2017.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Võta meiega ühendust või astu läbi!";

            return View();
        }
    }
}

Huvikool/Controllers/People2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Huvikool.Models;



namespace Huvikool.Controllers
{


    public class People2Controller : MyController
    {
        //private TagaridaEntities5 db = new TagaridaEntities5();

        // GET: People2
        [Authorize(Roles ="Lapsevanem,Admin,Juhendaja")]
        public ActionResult Index(string id = "")
        {

       
            var rolenames = id.Split(',');


            var persoonid = db.People;
             
                   


            var members = db.Members.ToList();
            var groups = db.Groups.ToList();

            if (User.IsInRole("Admin"))
            //return View(persoonid);
            {
                ViewBag.id = new SelectList((new TagaridaEntities2()).AspNetRoles.Select(x => x.Name), id);
                if (id == "") return View(persoonid.ToList());
                var userEmails = (new TagaridaEntities2())
                    .AspNetRoles
                    .ToList()
                    .Where(x => rolenames.Contains(x.Name))
                    .Select(x => x.AspNetUsers)
                    .SelectMany(x => x)
                    .Select(x => x.Email).ToList();
                return View(persoonid
                    .AsEnumerable()
                    .Where(x => userEmails.Contains(x.Email)).ToList());
            }
            if (User.IsInRole("Lapsevanem")) 
                return View(persoonid.Where(x => x.Parents.Select(y => y.Email).Contains(User.Identity.Name)).ToList());

            // kui on juhendaja, siis tuleks talle näidata
            // rühmade kaupa tema rühmade õpilasi
            //if (CurrentPerson.InstructedGroups.Count() > 0) 
            //    return View(groups.Where(x=> x.Instructors.Select(y=> y.Email).Contains(User.Identity.Name)).ToList());
 

            return RedirectToAction("Index", "Home");
        }

    


        [Authorize(Roles = "Lapsevanem, Admin, Juhendaja")]
        public ActionResult AddGr(int id, int grId)
        {
            Person p = db.People.Find(id);
            Group gr = db.Groups.Find(grId);
            if (p != null && gr != null)
            {
                try
                {
                    p.Members.Add(new Member { GroupId = grId , StartDate = DateTime.Today});
                    db.SaveChanges();
                }
                catch (Exception)
                {

                }
            }
            //            return View("Details", u);
            return RedirectToAction("Details", new { id = id });
        }

        [Authorize(Roles = "Lapsevanem, Admin, Juhendaja")]
        public ActionResult RemoveGr(int id, int grId)
        {
            Person p = db.People.Find(id);
            Group gr = db.Groups.Find(grId);
            if (p != null && gr != null)
            {
                try
                {
                    Member m = p.Members.Where(x => x.GroupId == grId && x.EndDate == null).SingleOrDefault();
                    if (m != null)
                    {
                        m.EndDate = DateTime.Today;
                        db.SaveChanges();
                    }
                }
                catch (Exception)
                {

                }
            }
            //            return View("Details", u);
            return RedirectToAction("Details", new { id = id });
        }



        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            var activities = (new TagaridaEntities5()).Members.Where(x => x.GroupId == id).Select(p => p.PersonId);
            ViewBag.Activities = db.Activities.AsEnumerable()
                
                .Where(p => activities.Contains(p.Id))
                .ToList()
                ;


            //ViewBag.Groups = db.Groups.ToList()
            //   .Except(person.Groups.ToList())
            //   .ToList();


            return View(person);
        }

        // GET: People2/Create
        [Authorize]
        public ActionResult Create()
        {
            return View(
                
                );
        }

        // POST: People2/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,FirstName,LastName,BirthDate,PictureId,IK")] Person person, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                ChangeDataFile(
                   file,
                   x => { person.PictureId = x; db.SaveChanges(); },
                   person.PictureId);


                if (User.IsInRole("Lapsevanem"))
                {
                    Person vanem = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                    vanem.Children.Add(person);
                    db.SaveChanges();
 

                }


                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People2/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            var pGroups = person.Members.Select(x => x.GroupId).ToList();
                        
            ViewBag.Groups = db.Groups.Where(z => z.MaxMembers > z.Members.Count()).ToList()
            //   .Except(person.Groups.ToList())
                .Where(x => !pGroups.Contains(x.Id))
               .ToList()
            ;


            return View(person);
        }

        // POST: People2/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,FirstName,LastName,BirthDate,PictureId,IK")] Person person, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                ChangeDataFile(
                              file,
                              x => { person.PictureId = x; db.SaveChanges(); },
                              person.PictureId);
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People2/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Huvikool/Views/People2/Create.cshtml
@model Huvikool.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Lisa uus kasutaja</h2>


@using (Html.BeginForm("Create", "People2", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kasutaja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new
                {
                    htmlAttributes = new
                    {
                        @class = "form-control"@*, disabled = "disabled"*@}
})
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        @*@Html.HiddenFor(x=> x.Email)
            @Html.Hidden("Email")
            <input type="hidden" name="Email" value="@Model.Email"/>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.PictureId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PictureId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PictureId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            <p class="control-label col-md-2"><strong> Lisa pilt </strong></p>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
                @*<img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
                    @Html.HiddenFor(x => x.PictureId)*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Loo kasutaja" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi nimekirja", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#datafile').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
    });</script>

Huvikool/Views/People2/Delete.cshtml
@model Huvikool.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Kustuta</h2>

<h3>Oled sa kindel, et soovid kasutaja kustutada?</h3>
<div>
    <h4>Kasutaja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictureId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PictureId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IK)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Kustuta" class="btn btn-default" /> |
            @Html.ActionLink("Tagasi nimekirja", "Index")
        </div>
    }
</div>

Huvikool/Views/People2/Details.cshtml
@model Huvikool.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Andmed</h2>

<div>
    <h4>Kasutajad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictureId)
        </dt>

        <dd>
            
                <img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
                @Html.HiddenFor(x => x.PictureId)
          
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IK)
        </dd>


    </dl>
</div>

    <table>
        <tr>
            <th width="30%"><h5><strong>Registreeritud huviring:</strong></h5></th>
            @*<th width="20%"></th>
                <th><h5><strong>Lisa/eemalda rolle:</strong></h5></th>*@
        </tr>
        <tr>
            <td>
                @foreach (var m in Model.Members)
                {
                    <p>@Html.ActionLink(@m.Group.Name, "Details"+"/"+m.Group.Id, "Groups")</p>

    
                }



            </td>
            <td />

            <td />
            <td />
            <td />
        </tr>
    </table>




<p>
    @Html.ActionLink("Muuda", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Tagasi nimekirja", "Index")
</p>

Huvikool/Views/People2/Edit.cshtml
@model Huvikool.Models.Person

@{
    ViewBag.Title = "Edit";
}

@*<h2>Edit</h2>*@


@using (Html.BeginForm("Edit", "People2", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kasutajad</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.PictureId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PictureId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PictureId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @*<strong>Kuidas pilti näha , oot? </strong>*@

        <div class="form-group">
            <p class="control-label col-md-2"> <strong> Muuda pilt </strong></p>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
                <img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
                @Html.HiddenFor(x => x.PictureId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IK, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvesta" class="btn btn-default" />
            </div>
        </div>
    </div>
}


        <table>
            <tr>
                <th width="30%"><h5><strong>Registreeritud huviring:</strong></h5></th>
                <th width="20%"></th>
                <th><h5><strong>Lisa huviringe:</strong></h5></th>
            </tr>
            <tr>
                <td>
                    @foreach (var m in Model.Members)
                    {
                        @*<p> @m.Group.Name</p>*@
                        <p>@Html.ActionLink("- " + m.Group.Name, "RemoveGr", new { id = Model.Id, GrId = m.Group.Id })</p>
                    }

                </td>
                <td />
                <td>
                    @foreach (Huvikool.Models.Group m in ViewBag.Groups)
                    {
                        <p>@Html.ActionLink("+ " + m.Name, "AddGr", new { id = Model.Id, GrId = m.Id })</p>
                    }

                </td>
                <td />
                <td />
                <td />
            </tr>
        </table>




    <div>
        @Html.ActionLink("Tagasi nimekirja", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#datafile').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $(document).ready(function () {
            $("#file").change(function () {
                readURL(this);
            });
        });</script>

Huvikool/Views/People2/Index.cshtml
@model IEnumerable<Huvikool.Models.Person>


@{
    ViewBag.Title = "Index";
}

@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <h2>Kasutajad</h2>
    }
    if (User.IsInRole("Lapsevanem"))
    {
        <h2>Lapsed</h2>
    }
    if (User.IsInRole("Juhendaja"))
    {
        <h2>Osalejad</h2>
        <li>@Html.ActionLink("Osalejad", "Index", "Members")</li>
    }
}



@*<h2>Kasutajad</h2>*@

@if (User.IsInRole("Admin"))
{
<form action="/People2/Index" name="selectForm" method="post">
    @Html.DropDownList("id", null, "-- kõik rollid --", new { @class = "form-control", style = "width:150px", onchange = "document.selectForm.submit()" })
   
</form>
}

<p>
    @Html.ActionLink("Lisa uus", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            Foto
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IK)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @* näitab pilti kui PictureId on olemas *@
                @if (item.PictureId != null)

                {
                    <img src="@Url.Action("Content", "My", new { id = item.PictureId })" height="100" />
                 }
 

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IK)
            </td>
            <td>
                @Html.ActionLink("Muuda", "Edit", new { id = item.Id }, new { @class = "btn btn-sm" })
                @Html.ActionLink("Detailid", "Details", new { id = item.Id }, new { @class = "btn btn-sm" })
                @Html.ActionLink("Kustuta", "Delete", new { id = item.Id }, new { @class = "btn btn-sm" })
            </td>
        </tr>
    }

</table>